In [ ]:
import numpy as np

# 1차원 ndArray 생성 (숫자 4개가 한 줄로 있는 배열)
np.array([1, 2, 3, 4])

arr1 = np.array([1, 2, 3, 4]) # numpy 배열임을 알려줌
arr2 = [1, 2, 3, 4]

# type = <class 'numpy.ndarray'>
# 넘파이로 이루어진 다차원 배열
print(type(arr1)) 

# type = <class 'list'>
# 파이썬 리스트 형태
print(type(arr2)) 

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# 1차원 배열 : 숫자가 한 줄로 늘어선 형태
# 2차원 배열 : 숫자가 가로와 세로로 된 표 모양
# 3차원 배열 : 2차원 배열이 여러 장 겹친 입체 모양

# 2차원 ndArray 생성
# 2차원 배열 = 1차원 배열 두개가 리스트로 묶인 형태
arr2 = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])

print("2차원 배열 arr2")                
print(arr2)

2차원 배열 arr2
[[1 2 3 4]
 [5 6 7 8]]


In [13]:
# 3차원 ndArray 생성
arr3 = np.array([[[1, 2, 3], [4, 5, 6]],
                [[2, 4, 6], [3, 5, 7]]])
print("3차원 배열 arr3")
print(arr3)             

3차원 배열 arr3
[[[1 2 3]
  [4 5 6]]

 [[2 4 6]
  [3 5 7]]]


In [ ]:
# 리스트 vs ndAraay
# 차원 

In [19]:
# ndim : 몇 차원 배열인지 알려줌
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# shape : 배열의 형태를 알려줌
print(arr1.shape) # (4,) = 숫자 4개가 있는 한 줄
print(arr2.shape) # (2, 4) = 2줄, 각 줄에 4칸
print(arr3.shape) # (2, 2, 3) = 2장(층), 각 장마다 2줄, 각 줄에 3칸

# size : 요소의 개수 (배열에 들어간 모든 숫자의 갯수를 알려줌)
print(arr1.size) # 4개
print(arr2.size) # 2 * 4 = 8개
print(arr3.size) # 2 * 2 * 3 = 12개

# dtype : 배열 요소의 데이터 타입
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)



1
2
3
(4,)
(2, 4)
(2, 2, 3)
4
8
12
int64
int64
int64


In [23]:
# ndarray.T : 전치행렬

arr = np.array([[1,2,3,],    
                [4,5,6]])

print("원래 배열")
print(arr)

print("전치 배열")
print(arr.T)

원래 배열
[[1 2 3]
 [4 5 6]]
전치 배열
[[1 4]
 [2 5]
 [3 6]]


In [26]:
# ndArray.flatten() : 1차원으로 펼치기

arr = np.array([[1,2,3,],    
                [4,5,6]])
                
print("원래 배열")                
print(arr)

print("1차원으로 펼친 배열")                
print(arr.flatten())

원래 배열
[[1 2 3]
 [4 5 6]]
1차원으로 펼친 배열
[1 2 3 4 5 6]


In [29]:
# ndArray.reshape() : 배열 모양 바꾸기, 원래 배열의 모습과 같아야 함
arr = np.array([1,2,3,4,5,6])
print("원래 배열")                
print(arr)

arr2 = arr.reshape(2, 3) # 2행 3열로 변환
print("2행 3열 배열")
print(arr2)

원래 배열
[1 2 3 4 5 6]
2행 3열 배열
[[1 2 3]
 [4 5 6]]


In [35]:
# ndArray.sum() : 합계구하기
# axis 옵션
# axis=0 : 열 방향 합
# axis=1 : 행 방향 합

arr = np.array([[1,2,3,],    
                [4,5,6]])

print("전체 합", arr.sum())
print("열방향 합(axis=0) :", arr.sum(axis=0))
print("행방향 합(axis=1) :", arr.sum(axis=1))

전체 합 21
열방향 합(axis=0) : [5 7 9]
행방향 합(axis=1) : [ 6 15]
